-- KANT BIBLE v2
-- Next.js + Supabase Auth + Database + Storage + Vercel
-- 기존 books / lectures / admins 데이터를 유지하면서 확장합니다.

create extension if not exists pgcrypto;

alter table public.lectures add column if not exists storage_path text;
alter table public.lectures add column if not exists file_size bigint;
alter table public.lectures add column if not exists mime_type text default 'text/html';
alter table public.lectures add column if not exists source_filename text;

create index if not exists lectures_book_published_idx
  on public.lectures(book_slug,is_published,updated_at desc);

create table if not exists public.admins(
  email text primary key,
  created_at timestamptz not null default now()
);
alter table public.admins enable row level security;

drop policy if exists "Admin can see own admin record" on public.admins;
create policy "Admin can see own admin record"
on public.admins for select to authenticated
using(lower(email)=lower(coalesce(auth.jwt()->>'email','')));

alter table public.lectures enable row level security;

drop policy if exists "Public can read published lectures" on public.lectures;
create policy "Public can read published lectures"
on public.lectures for select to anon,authenticated
using(is_published=true);

drop policy if exists "Admins can read all lectures" on public.lectures;
create policy "Admins can read all lectures"
on public.lectures for select to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can insert lectures" on public.lectures;
create policy "Admins can insert lectures"
on public.lectures for insert to authenticated
with check(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can update lectures" on public.lectures;
create policy "Admins can update lectures"
on public.lectures for update to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
))
with check(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can delete lectures" on public.lectures;
create policy "Admins can delete lectures"
on public.lectures for delete to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

create table if not exists public.posts(
  id bigint generated by default as identity primary key,
  book_slug text not null references public.books(slug) on delete cascade,
  nickname text not null check(char_length(nickname) between 2 and 20),
  title text not null check(char_length(title) between 2 and 80),
  content text not null check(char_length(content) between 2 and 4000),
  delete_password_hash text not null,
  status text not null default 'visible' check(status in ('visible','hidden')),
  created_at timestamptz not null default now()
);

create index if not exists posts_book_created_idx
  on public.posts(book_slug,created_at desc);

alter table public.posts enable row level security;

drop policy if exists "Public can read visible posts" on public.posts;
create policy "Public can read visible posts"
on public.posts for select to anon,authenticated
using(status='visible');

drop policy if exists "Admins can read all posts" on public.posts;
create policy "Admins can read all posts"
on public.posts for select to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can update posts" on public.posts;
create policy "Admins can update posts"
on public.posts for update to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
))
with check(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can delete posts" on public.posts;
create policy "Admins can delete posts"
on public.posts for delete to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

-- 익명 사용자는 DB에 직접 INSERT하지 않습니다.
-- Next.js /api/posts에서 검증과 속도 제한 후 service role로 INSERT합니다.

create table if not exists public.board_rate_limits(
  fingerprint text primary key,
  window_start timestamptz not null default now(),
  post_count integer not null default 0
);
alter table public.board_rate_limits enable row level security;

create or replace function public.claim_board_post(
  p_fingerprint text,
  p_limit integer default 5,
  p_window_minutes integer default 60
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare allowed boolean;
begin
  insert into public.board_rate_limits(fingerprint,window_start,post_count)
  values(p_fingerprint,now(),1)
  on conflict(fingerprint)
  do update set
    window_start=case
      when public.board_rate_limits.window_start < now()-make_interval(mins=>p_window_minutes)
      then now() else public.board_rate_limits.window_start end,
    post_count=case
      when public.board_rate_limits.window_start < now()-make_interval(mins=>p_window_minutes)
      then 1 else public.board_rate_limits.post_count+1 end
  returning(post_count<=p_limit) into allowed;
  return allowed;
end;
$$;

revoke all on function public.claim_board_post(text,integer,integer) from public;
revoke all on function public.claim_board_post(text,integer,integer) from anon;
revoke all on function public.claim_board_post(text,integer,integer) from authenticated;
grant execute on function public.claim_board_post(text,integer,integer) to service_role;

-- 50MB 비공개 HTML Storage
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('lectures','lectures',false,52428800,array['text/html','application/xhtml+xml'])
on conflict(id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Admins can read lecture storage" on storage.objects;
create policy "Admins can read lecture storage"
on storage.objects for select to authenticated
using(
  bucket_id='lectures' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);

drop policy if exists "Admins can upload lecture storage" on storage.objects;
create policy "Admins can upload lecture storage"
on storage.objects for insert to authenticated
with check(
  bucket_id='lectures' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);

drop policy if exists "Admins can update lecture storage" on storage.objects;
create policy "Admins can update lecture storage"
on storage.objects for update to authenticated
using(
  bucket_id='lectures' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
)
with check(
  bucket_id='lectures' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);

drop policy if exists "Admins can delete lecture storage" on storage.objects;
create policy "Admins can delete lecture storage"
on storage.objects for delete to authenticated
using(
  bucket_id='lectures' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);

insert into public.books(slug,name_ko,testament) values
('genesis','창세기','OT'),
('exodus','출애굽기','OT'),
('leviticus','레위기','OT'),
('numbers','민수기','OT'),
('deuteronomy','신명기','OT'),
('joshua','여호수아','OT'),
('judges','사사기','OT'),
('ruth','룻기','OT'),
('1-samuel','사무엘상','OT'),
('2-samuel','사무엘하','OT'),
('1-kings','열왕기상','OT'),
('2-kings','열왕기하','OT'),
('1-chronicles','역대상','OT'),
('2-chronicles','역대하','OT'),
('ezra','에스라','OT'),
('nehemiah','느헤미야','OT'),
('esther','에스더','OT'),
('job','욥기','OT'),
('psalms','시편','OT'),
('proverbs','잠언','OT'),
('ecclesiastes','전도서','OT'),
('song-of-songs','아가','OT'),
('isaiah','이사야','OT'),
('jeremiah','예레미야','OT'),
('lamentations','예레미야애가','OT'),
('ezekiel','에스겔','OT'),
('daniel','다니엘','OT'),
('hosea','호세아','OT'),
('joel','요엘','OT'),
('amos','아모스','OT'),
('obadiah','오바댜','OT'),
('jonah','요나','OT'),
('micah','미가','OT'),
('nahum','나훔','OT'),
('habakkuk','하박국','OT'),
('zephaniah','스바냐','OT'),
('haggai','학개','OT'),
('zechariah','스가랴','OT'),
('malachi','말라기','OT'),
('matthew','마태복음','NT'),
('mark','마가복음','NT'),
('luke','누가복음','NT'),
('john','요한복음','NT'),
('acts','사도행전','NT'),
('romans','로마서','NT'),
('1-corinthians','고린도전서','NT'),
('2-corinthians','고린도후서','NT'),
('galatians','갈라디아서','NT'),
('ephesians','에베소서','NT'),
('philippians','빌립보서','NT'),
('colossians','골로새서','NT'),
('1-thessalonians','데살로니가전서','NT'),
('2-thessalonians','데살로니가후서','NT'),
('1-timothy','디모데전서','NT'),
('2-timothy','디모데후서','NT'),
('titus','디도서','NT'),
('philemon','빌레몬서','NT'),
('hebrews','히브리서','NT'),
('james','야고보서','NT'),
('1-peter','베드로전서','NT'),
('2-peter','베드로후서','NT'),
('1-john','요한일서','NT'),
('2-john','요한이서','NT'),
('3-john','요한삼서','NT'),
('jude','유다서','NT'),
('revelation','요한계시록','NT')
on conflict(slug) do update set
  name_ko=excluded.name_ko,
  testament=excluded.testament;


-- 11. 개관 · 구조와 흐름 · 본문 연구 자료
create table if not exists public.book_resources(
  id bigint generated by default as identity primary key,
  book_slug text not null references public.books(slug) on delete cascade,
  section text not null check(section in ('overview','structure','research')),
  content_type text not null check(content_type in ('text','file')),
  title text not null,
  body_text text,
  storage_path text,
  source_filename text,
  mime_type text,
  file_size bigint,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists book_resources_book_section_idx
  on public.book_resources(book_slug,section,is_published,updated_at desc);

alter table public.book_resources enable row level security;

drop policy if exists "Public can read published book resources" on public.book_resources;
create policy "Public can read published book resources"
on public.book_resources for select to anon,authenticated
using(is_published=true);

drop policy if exists "Admins can read all book resources" on public.book_resources;
create policy "Admins can read all book resources"
on public.book_resources for select to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can insert book resources" on public.book_resources;
create policy "Admins can insert book resources"
on public.book_resources for insert to authenticated
with check(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can update book resources" on public.book_resources;
create policy "Admins can update book resources"
on public.book_resources for update to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
))
with check(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "Admins can delete book resources" on public.book_resources;
create policy "Admins can delete book resources"
on public.book_resources for delete to authenticated
using(exists(
  select 1 from public.admins a
  where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
));

-- 개관·구조·본문연구 파일용 50MB 비공개 버킷
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
  'book-resources',
  'book-resources',
  false,
  52428800,
  array[
    'text/html',
    'application/xhtml+xml',
    'application/pdf',
    'text/plain',
    'text/markdown',
    'image/png',
    'image/jpeg',
    'image/webp',
    'image/gif',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
)
on conflict(id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Admins can read book resource storage" on storage.objects;
create policy "Admins can read book resource storage"
on storage.objects for select to authenticated
using(
  bucket_id='book-resources' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);

drop policy if exists "Admins can upload book resource storage" on storage.objects;
create policy "Admins can upload book resource storage"
on storage.objects for insert to authenticated
with check(
  bucket_id='book-resources' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);

drop policy if exists "Admins can update book resource storage" on storage.objects;
create policy "Admins can update book resource storage"
on storage.objects for update to authenticated
using(
  bucket_id='book-resources' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
)
with check(
  bucket_id='book-resources' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);

drop policy if exists "Admins can delete book resource storage" on storage.objects;
create policy "Admins can delete book resource storage"
on storage.objects for delete to authenticated
using(
  bucket_id='book-resources' and exists(
    select 1 from public.admins a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  )
);


select 'KANT BIBLE v2 데이터베이스 준비 완료' as message;
