export type Testament = "OT" | "NT";
export type BibleBook = { slug:string; nameKo:string; testament:Testament; category:string };

export const BOOKS: BibleBook[] = [
  { slug: "genesis", nameKo: "창세기", testament: "OT" as const, category: "모세오경" },
  { slug: "exodus", nameKo: "출애굽기", testament: "OT" as const, category: "모세오경" },
  { slug: "leviticus", nameKo: "레위기", testament: "OT" as const, category: "모세오경" },
  { slug: "numbers", nameKo: "민수기", testament: "OT" as const, category: "모세오경" },
  { slug: "deuteronomy", nameKo: "신명기", testament: "OT" as const, category: "모세오경" },
  { slug: "joshua", nameKo: "여호수아", testament: "OT" as const, category: "역사서" },
  { slug: "judges", nameKo: "사사기", testament: "OT" as const, category: "역사서" },
  { slug: "ruth", nameKo: "룻기", testament: "OT" as const, category: "역사서" },
  { slug: "1-samuel", nameKo: "사무엘상", testament: "OT" as const, category: "역사서" },
  { slug: "2-samuel", nameKo: "사무엘하", testament: "OT" as const, category: "역사서" },
  { slug: "1-kings", nameKo: "열왕기상", testament: "OT" as const, category: "역사서" },
  { slug: "2-kings", nameKo: "열왕기하", testament: "OT" as const, category: "역사서" },
  { slug: "1-chronicles", nameKo: "역대상", testament: "OT" as const, category: "역사서" },
  { slug: "2-chronicles", nameKo: "역대하", testament: "OT" as const, category: "역사서" },
  { slug: "ezra", nameKo: "에스라", testament: "OT" as const, category: "역사서" },
  { slug: "nehemiah", nameKo: "느헤미야", testament: "OT" as const, category: "역사서" },
  { slug: "esther", nameKo: "에스더", testament: "OT" as const, category: "역사서" },
  { slug: "job", nameKo: "욥기", testament: "OT" as const, category: "시가·지혜서" },
  { slug: "psalms", nameKo: "시편", testament: "OT" as const, category: "시가·지혜서" },
  { slug: "proverbs", nameKo: "잠언", testament: "OT" as const, category: "시가·지혜서" },
  { slug: "ecclesiastes", nameKo: "전도서", testament: "OT" as const, category: "시가·지혜서" },
  { slug: "song-of-songs", nameKo: "아가", testament: "OT" as const, category: "시가·지혜서" },
  { slug: "isaiah", nameKo: "이사야", testament: "OT" as const, category: "대예언서" },
  { slug: "jeremiah", nameKo: "예레미야", testament: "OT" as const, category: "대예언서" },
  { slug: "lamentations", nameKo: "예레미야애가", testament: "OT" as const, category: "대예언서" },
  { slug: "ezekiel", nameKo: "에스겔", testament: "OT" as const, category: "대예언서" },
  { slug: "daniel", nameKo: "다니엘", testament: "OT" as const, category: "대예언서" },
  { slug: "hosea", nameKo: "호세아", testament: "OT" as const, category: "소예언서" },
  { slug: "joel", nameKo: "요엘", testament: "OT" as const, category: "소예언서" },
  { slug: "amos", nameKo: "아모스", testament: "OT" as const, category: "소예언서" },
  { slug: "obadiah", nameKo: "오바댜", testament: "OT" as const, category: "소예언서" },
  { slug: "jonah", nameKo: "요나", testament: "OT" as const, category: "소예언서" },
  { slug: "micah", nameKo: "미가", testament: "OT" as const, category: "소예언서" },
  { slug: "nahum", nameKo: "나훔", testament: "OT" as const, category: "소예언서" },
  { slug: "habakkuk", nameKo: "하박국", testament: "OT" as const, category: "소예언서" },
  { slug: "zephaniah", nameKo: "스바냐", testament: "OT" as const, category: "소예언서" },
  { slug: "haggai", nameKo: "학개", testament: "OT" as const, category: "소예언서" },
  { slug: "zechariah", nameKo: "스가랴", testament: "OT" as const, category: "소예언서" },
  { slug: "malachi", nameKo: "말라기", testament: "OT" as const, category: "소예언서" },
  { slug: "matthew", nameKo: "마태복음", testament: "NT" as const, category: "복음서" },
  { slug: "mark", nameKo: "마가복음", testament: "NT" as const, category: "복음서" },
  { slug: "luke", nameKo: "누가복음", testament: "NT" as const, category: "복음서" },
  { slug: "john", nameKo: "요한복음", testament: "NT" as const, category: "복음서" },
  { slug: "acts", nameKo: "사도행전", testament: "NT" as const, category: "역사서" },
  { slug: "romans", nameKo: "로마서", testament: "NT" as const, category: "바울서신" },
  { slug: "1-corinthians", nameKo: "고린도전서", testament: "NT" as const, category: "바울서신" },
  { slug: "2-corinthians", nameKo: "고린도후서", testament: "NT" as const, category: "바울서신" },
  { slug: "galatians", nameKo: "갈라디아서", testament: "NT" as const, category: "바울서신" },
  { slug: "ephesians", nameKo: "에베소서", testament: "NT" as const, category: "바울서신" },
  { slug: "philippians", nameKo: "빌립보서", testament: "NT" as const, category: "바울서신" },
  { slug: "colossians", nameKo: "골로새서", testament: "NT" as const, category: "바울서신" },
  { slug: "1-thessalonians", nameKo: "데살로니가전서", testament: "NT" as const, category: "바울서신" },
  { slug: "2-thessalonians", nameKo: "데살로니가후서", testament: "NT" as const, category: "바울서신" },
  { slug: "1-timothy", nameKo: "디모데전서", testament: "NT" as const, category: "바울서신" },
  { slug: "2-timothy", nameKo: "디모데후서", testament: "NT" as const, category: "바울서신" },
  { slug: "titus", nameKo: "디도서", testament: "NT" as const, category: "바울서신" },
  { slug: "philemon", nameKo: "빌레몬서", testament: "NT" as const, category: "바울서신" },
  { slug: "hebrews", nameKo: "히브리서", testament: "NT" as const, category: "공동서신" },
  { slug: "james", nameKo: "야고보서", testament: "NT" as const, category: "공동서신" },
  { slug: "1-peter", nameKo: "베드로전서", testament: "NT" as const, category: "공동서신" },
  { slug: "2-peter", nameKo: "베드로후서", testament: "NT" as const, category: "공동서신" },
  { slug: "1-john", nameKo: "요한일서", testament: "NT" as const, category: "공동서신" },
  { slug: "2-john", nameKo: "요한이서", testament: "NT" as const, category: "공동서신" },
  { slug: "3-john", nameKo: "요한삼서", testament: "NT" as const, category: "공동서신" },
  { slug: "jude", nameKo: "유다서", testament: "NT" as const, category: "공동서신" },
  { slug: "revelation", nameKo: "요한계시록", testament: "NT" as const, category: "묵시문학" },
];

export const BOOK_MAP = new Map(BOOKS.map((book) => [book.slug, book]));
export function getBook(slug:string) { return BOOK_MAP.get(slug); }
